apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - coda-ex.brazilsouth.cloudapp.azure.com
      secretName: tls-secret
  rules:
    - host: coda-ex.brazilsouth.cloudapp.azure.com
      http:
        paths:
          - backend:
              serviceName: aks-helloworld
              servicePort: 80
            path: /hello-world-one
          - backend:
              serviceName: ingress-demo
              servicePort: 80
            path: /hello-world-two
          - backend:
              serviceName: bpp
              servicePort: 80
            path: /elixir
          - backend:
              serviceName: aks-helloworld
              servicePort: 80
            path: /(.*)
