apiVersion: v1
kind: Service
metadata:
  name: {{ include "bpp.fullname" . }}
  labels:
    {{- include "bpp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9568
      targetPort: 9568
      name: prometheus
  selector:
    {{- include "bpp.selectorLabels" . | nindent 4 }}
