apiVersion: v1
kind: Service
metadata:
  name: bpp
  labels:
    {{- include "bpp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: http
    - port: 9568
      targetPort: 9568
      protocol: TCP
      name: metrics
  selector:
    app: bpp
