apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpp
  labels:
    app: bpp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpp
  template:
    metadata:
      labels:
        app: bpp
    spec:
      containers:
        - name: bpp
          image: codaacr.azurecr.io/app:dev
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@bpp-postgresql:5432/example_dev
            - name: SECRET_KEY_BASE
              value: "mWwrEqegM+BRDhOQ8G27fWYST2F17XgNTmTLg5OH92QLa9obBvnQChnbPX6Lve8K"
          ports:
            - containerPort: 4000
            - containerPort: 9568
